config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users

  resources :flats do
    resources :bookings, only: [:show, :new, :create]
  end

  resources :bookings, only: [:index, :destroy]

  # get "/about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  validates :starts_at, :ends_at, :messages, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  belongs_to :user
  # has_many :reviews, dependent: :destroy

  # cloudinary
  has_many_attached :photos

  # geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, :price_per_night, :number_of_guests, :address, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :flats, through: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: allow-list approach
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index
  skip_policy_scope ⇒ home#home

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_sign_in_path_for(resources)
    flats_path
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flat, only: [:new, :create]
  before_action :set_booking, only: [:show, :destroy]

  def index
    @bookings = current_user.bookings.includes(:flat)
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.flat = @flat
    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully deleted.' , status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at, :messages)
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = policy_scope(Flat)
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat}),
        marker_html: render_to_string(partial: "marker"),
      }
    end
    if params[:query].present?
      sql_subquery = <<-SQL
        title ILIKE :query OR
        address ILIKE :query OR
        CAST(price_per_night AS TEXT) ILIKE :query OR
        CAST(number_of_guests AS TEXT) ILIKE :query
      SQL
      @flats = @flats.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat
    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :address, :description, :price_per_night, :number_of_guests, photos: [])
  end

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home
  skip_after_action :verify_policy_scoped, only: :home
  skip_policy_scope ⇒ :home

  def home
    @resource = User.new
    @resource_name = :user
    @devise_mapping = Devise.mappings[:user]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def country_select_options
    ISO3166::Country.all.map { |country| [country.translations['en'], country.alpha2] }
  end
end

app/views/bookings/index.html.erb
<!--banner-->
<div class="banner banner-relative">
  <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <h1 class="banner-title card-title my-4">My Bookings</h1>
</div>
<!--banner-->
<!--body-->
<div class="body-container">
  <div class="row mt-1", style="height: 300px;">
    <% if @bookings.any? %>
      <% @bookings.each do |booking| %>
        <div class="col-md-4">
          <!--reservation-card-->
          <div class="card">
            <% if booking.flat.photos.attached? %>
              <!--         Cloudinary-->
              <%= cl_image_tag booking.flat.photos.first.key, class: "images" %>
            <% else booking.flat.image_url.present? %>
              <!--         Unsplash-->
              <%= image_tag bookingflat.image_url, class: "images", alt: flat.title %>
            <% end %>
            <div class="gap-1 p-3">
              <H2><%= booking.flat.title %></H2>
              <p><%= booking.flat.address%></p>
              <div class="d-flex gap-4">
                <p>From: <%= booking.starts_at %></p>
                <p>to: <%= booking.ends_at %></p>
              </div>
            </div>
            <div class="d-flex justify-content-center mx-4">
              <p>
                <%= link_to 'View', flat_booking_path(booking.flat, booking), class: 'brown-button' %>
              </p>
            </div>
          <% end %>
        <% else %>
          <p>You have no bookings.</p>
        <% end %>
      </div>
      <!--reservation-card-->
    </div>
    <div class="d-flex justify-content-end mb-2">
      <%= link_to "Back", flats_path, class: "brown-button m-4" %>
    </div>
  </div>
</div>
<!--body-->

app/views/bookings/new.html.erb
<!--banner-->
<div class="banner banner-relative mb-5">
  <% if @flat.photos.attached? %>
    <!--cloudinary-->
    <%= cl_image_tag @flat.photos.first.key, alt: "#{@flat.title} - image of the apartment", class: "banner-img img-fluid", crop: :thumb, gravity: :face %>
    <!--cloudinary-->
  <% else %>
    <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <% end %>
  <h1 class="banner-title card-title my-4">Booking for <%= @flat.title %></h1>
  <div class="banner-text card-body d-flex flex-column">
    <p><%= @flat.description %></p>
    <div class="d-flex gap-1">
      <p class="card-text"><%= @flat.address %></p>
    </div>
    <div class="d-flex justify-content-start gap-4">
      <p class="card-text">
        <i class="fas fa-users"></i> <%= @flat.number_of_guests %>
      </p>
      <p class="card-text gap-4">
        <i class="fas fa-dollar-sign"></i> <%= @flat.price_per_night %>
      </p>
    </div>
  </div>
</div>
<!--banner-->
<div class="container mb-4">
  <div class="row justify-content-center mt-5">
    <div class="card col-md-8">
      <div class="card-body gap-4">
        <%= form_with(model: [@flat, @booking], local: true) do |f| %>
          <div class="d-flex gap-4">
            <div class="form-group my-4">
              <%= f.label :starts_at %>
              <%= f.date_select :starts_at, class: "form-control" %>
            </div>
            <div class="form-group my-4">
              <%= f.label :ends_at %>
              <%= f.date_select :ends_at, class: "form-control" %>
            </div>
          </div>
          <div class="form-group my-4">
            <%= f.label :messages %>
            <%= f.text_area :messages, class: "form-control" %>
          </div>
          <div class="d-flex justify-content-end gap-4">
            <%= link_to 'Back', flat_path(@flat), class: "btn btn-primary button" %>
            <%= f.submit "Book it!", class: "btn btn-primary button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<!--banner-->
<div class="banner banner-relative">
  <% if @booking.flat.photos.attached? %>
    <!--cloudinary-->
    <%= cl_image_tag @booking.flat.photos.first.key, alt: "#{@booking.flat.title} - image of the apartment", class: "banner-img img-fluid", crop: :thumb, gravity: :face %>
    <!--cloudinary-->
  <% else %>
    <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <% end %>
  <h1 class="banner-title card-title my-4">Booking Details</h1>
</div>
<!--banner-->
<div class="body-container">
  <div class="row justify-content-center mt-5">
    <div class="mb-4 w-25">
      <h2 class="card-title "><%= @booking.flat.title %></h2>
      <p class="card-text "><strong>Address:</strong><br> <%= @booking.flat.address %></p>
      <div class="d-flex">
        <p class="card-text "><strong>Start Date:</strong> <%= @booking.starts_at %></p>
        <p class="card-text "><strong>End Date:</strong> <%= @booking.ends_at %></p>
      </div>
      <p class="card-text "><strong>Messages:</strong><br> <%= @booking.messages %></p>
    </div>
    <div class="d-flex justify-content-between ">
      <%= link_to "Back", bookings_path, class: "brown-button" %>
      <%= link_to "Cancel", booking_path(@booking), class: "brown-button", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  </div>

app/views/flats/_info_window.html.erb
<h2><%= flat.title %></h2>
<p><%= flat.address %></p>

app/views/flats/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<!--<div class="badge rounded-pill bg-primary fs-6">-->
  <%#= flat.name %>
<!--</div>-->

app/views/flats/edit.html.erb
<!--banner-->
<div class="banner banner-relative">
  <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <h1 class="banner-title card-title my-4">Modify informations</h1>
</div>
<!--banner-->
<!--form-->
<div class="body-container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card-body">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :title %>
          <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
          <%= f.input :description %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <div class="d-flex justify-content-between mt-2">
            <%= link_to "Back", flat_path(@flat), class: "brown-button" %>
            <div class="d-flex justify-content-end gap-4">
              <%= f.submit "Submit", class: "brown-button" %>
            <% end %>
            <% if policy(@flat).destroy? %>
              <%= link_to "Delete", flat_path(@flat), class: "brown-button", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--form-->

app/views/flats/index.html.erb
<!--banner-->
<div class="banner banner-relative">
  <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <div class="banner-search-bar row justify-content-center">
    <div class="col-sm-8 my-5">
      <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
        <%= submit_tag "Search", name: "", class: "brown-button" %>
      <% end %>
    </div>
  </div>
</div>
<!--banner-->
<!-- body -->
<div class="body-container">
  <!--appartement cards-->
  <div class="row mt-1">
    <% @flats.each do |flat| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <% if flat.photos.attached? %>
            <!-- Cloudinary -->
            <%= cl_image_tag flat.photos.first.key, class: "images" %>
          <% else flat.image_url.present? %>
            <!-- Unsplash  -->
            <%= image_tag flat.image_url, class: "images", alt: flat.title %>
          <% end %>
          <div class="card-body d-flex flex-column">
            <h2 class="card-title my-4 h4"><%= flat.title %></h2>
            <p class="card-text"><%= flat.address %></p>
            <div class="d-flex gap-1">
            </div>
            <p class="card-text b-4"><%= flat.description %></p>
            <div class="d-flex justify-content-start gap-4">
              <p class="card-text">
                <i class="fas fa-users"></i> <%= flat.number_of_guests %>
              </p>
              <p class="card-text gap 4">
                <i class="fas fa-dollar-sign"></i> <%= flat.price_per_night %>
              </p>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to 'View Details', flat_path(flat), class: "brown-button" %>
            </div>
          </div> 
        </div>
      </div>
    <% end %>
  </div>
  <!--appartement cards-->
  <!--map-->
  <!--  <div style="width: 100%; height: 200px;"
  data-controller="map"
  data-map-markers-value="<%#= @markers.to_json %>"
  data-map-api-key-value="<%#= ENV['MAPBOX_API_KEY'] %>">
  </div>-->
  <!--map-->
</div>
<!-- body -->

app/views/flats/new.html.erb
<!-- app/views/flats/new.html.erb -->
<!--banner-->
<div class="banner banner-relative">
  <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <h1 class="banner-title card-title my-4">Modify informations</h1>
</div>
<!--banner-->
<!--form-->
<div class="body-container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card-body">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :title %>
          <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
          <%= f.input :description %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <div class="d-flex justify-content-between mt-2">
            <%= link_to "Back", flats_path, class: "brown-button" %>
            <%= f.submit "Submit", class: "brown-button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!--form-->

app/views/flats/show.html.erb
<!--banner-->
<div class="banner banner-relative">
  <% if @flat.photos.attached? %>
    <!--cloudinary-->
    <%= cl_image_tag @flat.photos.first.key, alt: "#{@flat.title} - image of the apartment", class: "banner-img img-fluid", crop: :thumb, gravity: :face %>
    <!--cloudinary-->
  <% else %>
    <%= image_tag "banner.png", alt: "banner of the website", class: "banner-img img-fluid" %>
  <% end %>
  <h1 class="banner-title card-title my-4"><%= @flat.title %></h1>
  <div class="banner-text card-body d-flex flex-column">
    <p><%= @flat.description %></p>
    <div class="d-flex gap-1">
      <p class="card-text"><%= @flat.address %></p>
    </div>
    <div class="d-flex justify-content-start gap-4">
      <p class="card-text">
        <i class="fas fa-users"></i> <%= @flat.number_of_guests %>
      </p>
      <p class="card-text gap-4">
        <i class="fas fa-dollar-sign"></i> <%= @flat.price_per_night %>
      </p>
    </div>
  </div>
</div>
<!--banner-->
<!--body-->
<div class="body-container">
  <div class="row">
    <% @flat.photos.each do |photo| %>
      <div class="col-md-4 mb-4">
        <div class="h-100">
          <%= cl_image_tag photo.key, class: "images" %>
        </div>
      </div>
    <% end %>
    <!--buttons-->
    <div class="d-flex justify-content-between gap-4 my-4">
      <div class="d-flex justify-content-start">
        <%= link_to "Back", flats_path, class: "brown-button" %>
      </div>
      <div class="d-flex justify-content-end gap-4">
        <% if policy(@flat).edit? %>
          <%= link_to "Modify", edit_flat_path(@flat), class: "brown-button" %>
        <% end %>
        <%= link_to "Book it!", new_flat_booking_path(@flat), class: "brown-button" %>
      </div>
    </div>
  </div>
</div>
<!--body-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbLike</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "at-home-510cfd.webflow", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "normalize", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "webflow", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <!--   <p class="notice"><%#= notice %></p>
    <p class="alert"><%#= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my about page</h1>

app/views/pages/home.html.erb
<div class="homepage-container">
  <div class="homepage-col-left">
    <h1 class="homepage-title">Find a flat to stay</h1>
    <p class="homepage-text">It has never been easier to find a place. With At Home, you can find the best and most convenient apartment wherever you want and feel like you are at home.</p>
    <button type="button" class="brown-button" data-bs-toggle="modal" data-bs-target="#reg-modal">
      Start now
    </button>
  </div>
  <div class="homepage-col-right">
    <%= image_tag 'homepage-img.png', class: "homepage-img" %>
  </div>
</div>
<script type="module">
  import "webflow";
</script>
<%#= javascript_pack_tag 'webflow' %>
<!--sign up modal-->
<div class="modal fade bd-example-modal-lg" id="reg-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <%= render partial: "devise/shared/signup", locals: { resource: @resource, resource_name: @resource_name, devise_mapping: @devise_mapping } %>
      </div>
    </div>
  </div>
</div>
<!--sign up modal-->
<!--log in modal-->
<div class="modal fade bd-example-modal-lg" id="log-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <%= render partial: "devise/shared/login", locals: { resource: @resource, resource_name: @resource_name, devise_mapping: @devise_mapping } %>
      </div>
    </div>
  </div>
</div>
<!--log in modal-->
<!--forgot password modal-->
<div class="modal fade bd-example-modal-lg" id="forpass-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <%= render partial: "devise/shared/forgot_password", locals: { resource: @resource, resource_name: @resource_name, devise_mapping: @devise_mapping } %>
      </div>
    </div>
  </div>
</div>
<!--forgot password modal-->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-left">
    <%#= link_to "#", class: "" do %>
      <%= image_tag('at_home_logo.png', class: "navbar-logo") %>
      <%# end %>
      <!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
      <%= link_to "Home", flats_path, class: "navbar-link" %>
      <%= link_to 'Contact', "#", class:"navbar-link"  %>
      <%= link_to 'Service', "#", class:"navbar-link" %>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item active mx-2">
            <%= link_to "Rent now !", new_flat_path, class: "brown-button" %>
          </li>
          <!--          <li class="nav-item active mx-2">-->
          <%#= link_to "Home", flats_path, class: "navbar-button w-button" %>
          <!--          </li>-->
          <li class="nav-item mx-1">
            <%= link_to "My Bookings", bookings_path, class: "brown-button" %>
          </li>
          <li class="nav-item dropdown mx-2">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag("user-logo.png", alt: "User logo", class: "avatar user-logo") %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <button type="button" class="brown-button" data-bs-toggle="modal" data-bs-target="#log-modal">
            Log in
          </button>
          <button type="button" class="brown-button" data-bs-toggle="modal" data-bs-target="#reg-modal">
            Sign up
          </button>
        <% end %>
      </ul>
    </div>
  </div>